// dapp-template/src/components/BurnGala.vue
<template>
  <div class="burn-container">
    <h2>Burn GALA</h2>
    
    <div class="burn-form">
      <div class="input-group">
        <input 
          type="number" 
          v-model="burnAmount" 
          :min="0"
          step="1"
          placeholder="Amount to burn"
          :disabled="isProcessing"
        />
        <span class="currency">GALA</span>
      </div>
      <small class="fee-notice">Network fee: 1 GALA</small>

      <button 
        @click="burnTokens" 
        :disabled="!isValidAmount || isProcessing"
      >
        {{ isProcessing ? 'Processing...' : 'Burn Tokens' }}
      </button>

      <p v-if="error" class="error">{{ error }}</p>
      <p v-if="success" class="success">{{ success }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { BrowserConnectClient } from '@gala-chain/connect'

const props = defineProps<{
  walletAddress: string
  metamaskClient: BrowserConnectClient
}>()

const burnAmount = ref<number | null>(null)
const isProcessing = ref(false)
const error = ref('')
const success = ref('')

const isValidAmount = computed(() => {
  return burnAmount.value !== null && burnAmount.value > 0
})

async function burnTokens() {
  if (!isValidAmount.value || !props.walletAddress) return
  
  error.value = ''
  success.value = ''
  isProcessing.value = true

  try {
    const burnTokensDto = {
      owner: props.walletAddress,
      tokenInstances: [{
        quantity: burnAmount.value?.toString(),
        tokenInstanceKey: {
          collection: "GALA",
          category: "Unit",
          type: "none",
          additionalKey: "none",
          instance: "0"
        }
      }],
      uniqueKey: `january-2025-event-${import.meta.env.VITE_PROJECT_ID}-${Date.now()}`
    }

    const signedBurnDto = await props.metamaskClient.sign("BurnTokens", burnTokensDto)
    
    const response = await fetch(`${import.meta.env.VITE_BURN_GATEWAY_API}/BurnTokens`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(signedBurnDto)
    })

    if (!response.ok) {
      throw new Error('Failed to burn tokens')
    }

    success.value = `Successfully burned ${burnAmount.value} GALA`
    burnAmount.value = null
  } catch (err) {
    console.error(`Error burning tokens: ${err}`, err)
    error.value = err instanceof Error ? err.message : 'Failed to burn tokens'
  } finally {
    isProcessing.value = false
  }
}
</script>

<style scoped>
.burn-container {
  margin: 20px 0;
  padding: 20px;
  border: 1px solid #ddd;
  border-radius: 8px;
}

.burn-form {
  display: flex;
  flex-direction: column;
  gap: 15px;
  max-width: 300px;
  margin: 0 auto;
}

.input-group {
  position: relative;
  display: flex;
  align-items: center;
}

input {
  width: 100%;
  padding: 8px;
  padding-right: 60px;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.currency {
  position: absolute;
  right: 10px;
  color: #666;
}

button {
  padding: 10px;
  background-color: #4CAF50;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:disabled {
  background-color: #cccccc;
  cursor: not-allowed;
}

.error {
  color: #ff4444;
  text-align: center;
}

.success {
  color: #4CAF50;
  text-align: center;
}

.fee-notice {
  color: #666;
  font-size: 0.8em;
  text-align: right;
  margin-top: -10px;
}
</style>

// react-vite-client/src/components/BurnGala.tsx
"use client";

import { useState, useEffect } from "react";
import { BrowserConnectClient } from "@gala-chain/connect";

interface BurnGalaProps {
  walletAddress: string;
}

export default function BurnGala({ walletAddress }: BurnGalaProps) {
  const [amount, setAmount] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState<string>("");
  const [metamaskClient, setMetamaskClient] =
    useState<BrowserConnectClient | null>(null);

  useEffect(() => {
    setMetamaskClient(new BrowserConnectClient());
  }, []);

  const handleBurn = async () => {
    try {
      setLoading(true);
      setStatus("");

      if (!walletAddress) {
        throw new Error("No wallet connected");
      }

      const burnAmount = parseFloat(amount);
      if (isNaN(burnAmount) || burnAmount <= 0) {
        throw new Error("Invalid amount");
      }

      if (!metamaskClient) {
        throw new Error("Client not initialized");
      }

      const burnTokensDto = {
        owner: walletAddress,
        tokenInstances: [
          {
            quantity: amount,
            tokenInstanceKey: {
              collection: "GALA",
              category: "Unit",
              type: "none",
              additionalKey: "none",
              instance: "0",
            },
          },
        ],
        uniqueKey: `burn-${Date.now()}`,
      };

      const signature = await metamaskClient.sign(burnTokensDto);

      const response = await fetch(`${import.meta.env.VITE_API_URL}/burn`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(signature),
      });

      if (!response.ok) {
        throw new Error("Failed to burn tokens");
      }

      const result = await response.json();
      setStatus(
        `Successfully burned ${amount} GALA. Transaction: ${result.transactionId}`,
      );
      setAmount("");
    } catch (error) {
      console.error("Failed to burn GALA:", error);
      setStatus(
        `Error: ${error instanceof Error ? error.message : "Unknown error occurred"}`,
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-4 border rounded-lg shadow-sm">
      <h2 className="text-xl font-bold mb-4">Burn GALA</h2>
      <div className="flex flex-col gap-4">
        <input
          type="number"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
          placeholder="Amount to burn"
          className="border p-2 rounded"
          min="0"
          step="0.000001"
        />
        <button
          onClick={handleBurn}
          disabled={loading || !amount}
          className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 disabled:bg-gray-400"
        >
          {loading ? "Processing..." : "Burn GALA"}
        </button>
        {status && (
          <p
            className={`mt-2 ${status.startsWith("Error") ? "text-red-500" : "text-green-500"}`}
          >
            {status}
          </p>
        )}
      </div>
    </div>
  );
}
